version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: video-test-mysql
      working_dir: /application
      volumes:
        - ./storage/docker/db.data:/var/lib/mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE="${DB_DATABASE}"
        - MYSQL_USER="${DB_USERNAME}"
        - MYSQL_PASSWORD="${DB_PASSWORD}"
      ports:
        - "13306:3306"
      expose:
        - "3306"
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"

    webserver:
      image: nginx:alpine
      container_name: video-test-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8011:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: video-test-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

